### ISSUE TITLE
[QA] Test User Info Endpoint

### ISSUE THREAD

**Issue by anra54** [purwaren/moflip-api#67]

**Comment by drmwnarief28** [comment]
| Aspect Testing   | API       | Parameter  | Request Body | Expected Result | Actual Result | Status (P/F) | Description |
|------------------|-----------|------------|--------------|-----------------|---------------|--------------|-------------|
| Auth/otp-request | user-info | /user-info | -            | -               | code 200      | As Expected  | P           |
|                  |           |            |              |                 | email         |              |             |
|                  |           |            |              |                 | role          |              |             |
