### ISSUE TITLE
[QA] Test Resend OTP Endpoint

### ISSUE THREAD

**Issue by anra54** [purwaren/moflip-api#68]

**Comment by drmwnarief28** [comment]
| Aspect Testing   | API                      | Parameter | Request Body | Expected Result | Actual Result | Status (P/F) | Description                    |
|------------------|--------------------------|-----------|--------------|-----------------|---------------|--------------|--------------------------------|
| Auth/otp-request | /api/v1/auth/otp-request | -         | token        | code 200        | As Expected   | P            | Mengirimkan otp baru ke email  |
|                  |                          |           |              | message         |               |              |                                |
|                  |                          |           |              | data : {}       |               |              |                                |
