### ISSUE TITLE
[QA] Test Activate/Deactivate 2FA Endpoints

### ISSUE THREAD

**Issue by anra54** [purwaren/moflip-api#69]

**Comment by drmwnarief28** [comment]
| Aspect Testing   | API                    | Parameter | Request Body  | Expected Result | Actual Result | Status (P/F) | Description                                                                                              |
|------------------|------------------------|-----------|---------------|-----------------|---------------|--------------|----------------------------------------------------------------------------------------------------------|
| 2FA/setup        | /api/v1/2fa/setup      | -         | type : GOOGLE | code 200        | As Expected   | P            | untuk url API, tidak dapat diakses 404. Sedangkan ketika ditambahkan ../v1/setting/2fa/.. dapat diakses  |
|                  |                        |           |               | message         |               |              | tidak menampilkan token                                                                                  |
|                  |                        |           |               | token           |               |              |                                                                                                          |
|                  |                        |           |               | secret          |               |              |                                                                                                          |
|                  |                        |           |               | qr_code         |               |              |                                                                                                          |
|                  |                        |           |               |                 |               |              |                                                                                                          |
| 2FA/Activation   | /api/v1/2fa/activation | -         | type : GOOGLE | code 200        | As Expected   | P            | Dicoba tanpa menggunakan token dan berhasil                                                              |
|                  |                        |           | token         | message         |               |              |                                                                                                          |
|                  |                        |           | otp           | data :{}        |               |              |                                                                                                          |
|                  |                        |           |               |                 |               |              |                                                                                                          |
| 2FA/deactivation | /api/v1/2fa/setup      | -         | type : EMAIL  | code 200        | As Expected   | P            | Mengirmkan token saja                                                                                    |
|                  |                        |           |               | message         |               |              |                                                                                                          |
|                  |                        |           |               | token           |               |              |                                                                                                          |
|                  |                        |           |               | secret          |               |              |                                                                                                          |
|                  |                        |           |               | qr_code         |               |              |                                                                                                          |
|                  |                        |           |               |                 |               |              |                                                                                                          |
| 2FA/Activation   | /api/v1/2fa/activation | -         | type : EMAIL  | code 200        | As Expected   | P            | Dicoba menggunakan token dan berhasil                                                                    |
|                  |                        |           | token         | message         |               |              |                                                                                                          |
|                  |                        |           | otp           | data :{}        |               |              |                                                                                                          |

**Comment by drmwnarief28** [comment]
- Untuk url API 2fa, memerlukan tambahan setting/2fa/..
- Untuk aktivasi saat menggunakan google respon yang diberikan hanya secret dan qr_code
- Untuk aktivasi email (deaktivasi 2fa) responsnya memberikan token
![WhatsApp Image 2021-11-22 at 16 58 45](https://user-images.githubusercontent.com/54920443/142849332-ccb680bb-dbdd-4045-b9ec-0443f4b325d2.jpeg)
