### ISSUE TITLE
[QA] Test Login/Logout & Verify Endpoints

### ISSUE THREAD

**Issue by anra54** [purwaren/moflip-api#70]

**Comment by drmwnarief28** [comment]
**Aspect Testing** | **API** | **Parameter** | **Request Body** | **Expected Result** | **Actual Result** | **Status (P/F)** | **Description** | **** | **** 
---|---|---|---|---|---|---|---|---|---
 Auth/login | /api/v1/auth/login | - | type : email | Code 200 | As Expected | P |   |  |  
  |  |  | username : ayamkuah0@gmail.com | message |  |  |   |  |  
  |  |  | password : testPassword123 | data : { token } |  |  |   |  |  
  |  |  | type : phone |  |  |  | pending  |  |  
  |  |  | username : 000000000 |  |  |  |   |  |  
  |  |  | password : testPassword124 |  |  |  |   |  |  
  |  |  |  |  |  |  |   |  |  
 Auth/verify | /api/v1/auth/verify | - | token | code 200 | As Expected | P |   |  |  
  |  |  | otp | message |  |  |   |  |  
 Auth/logout | /api/v1/auth/logout | - | - | code 200 | As Expected | P | Set auth dengan token yang didapat dari verify  |  |
