### ISSUE TITLE
[QA] Test Register & Activation Endpoints

### ISSUE THREAD

**Issue by anra54** [purwaren/moflip-api#71]

**Comment by drmwnarief28** [comment]
| Aspect Testing  | API                     | Parameter | Request Body                | Expected Result          | Actual Result | Status (P/F) | Description                                                                             |
|-----------------|-------------------------|-----------|-----------------------------|--------------------------|---------------|--------------|-----------------------------------------------------------------------------------------|
| Auth/register   | /api/v1/auth/register   | -         | email : ayamkuah0@gmail.com | give code 200, and token | As Expected   | P            | [JSON] code: 200 ; message : "OK"; token : [string]                                     |
|                 |                         |           | name : soto ayam            |                          |               |              | regist dengan email yang sama juga mendapatkan respon yang sama dengan expected result  |
|                 |                         |           | password : testPassword123  |                          |               |              |                                                                                         |
|                 |                         |           |                             |                          |               |              |                                                                                         |
| Auth/activision | /api/v1/auth/activation | -         | token : //from register     | code 200                 | Fail          | F            | error code 400                                                                          |
|                 |                         |           | otp                         | message                  |               |              | message : "Your request is in a bad format."                                            |
|                 |                         |           |                             | data :{}                 |               |              |                                                                                         |
|                 |                         |           |                             |                          |               |              |                                                                                         |

**Comment by drmwnarief28** [comment]
**Regist dengan email yang sama**

![image](https://user-images.githubusercontent.com/54920443/142724899-a92f2f7a-bef6-4091-9a3d-270ee0e8b16c.png)
![image](https://user-images.githubusercontent.com/54920443/142724916-08d731b3-4328-4f76-8fdc-34b006f70ca1.png)

**[POST] Activation**
![image](https://user-images.githubusercontent.com/54920443/142724962-37da5a1f-c425-4613-b70f-9c5f279efede.png)
