### ISSUE TITLE
[QA] Test API CRU Ref Coin

### ISSUE THREAD

**Issue by anra54** [purwaren/moflip-api#80]

**Comment by drmwnarief28** [comment]
| Aspect Testing | API | Parameter | Request Body | Expected Result | Actual Result | Status (P/F) | Description |
|---|---|---|---|---|---|---|---|
| [POST] create ref-coin | /ref-coins |  | symbol : "TRX | ref-coins created | As Expected | P | created by bisa dilakukan oleh user dengan role member |
|  |  |  | name : "Tron" |  |  |  |  |
|  |  |  | network : "dummy_network_tron" |  |  |  |  |
|  |  |  | api_url : "tron_dummy.com" |  |  |  |  |
|  |  |  | flag_enable : true |  |  |  |  |
|  |  |  | pool_wallet : "tron" |  |  |  |  |
|  |  |  | description : "dummy_description" |  |  |  |  |
|  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |
| [GET] ref-coins | /ref-coins | - | - | Show list of ref-coins | As Expected | P |  |
| [GET] detail ref-coin | /ref-coins/:id | - | - | Show detail ref coin with spesifc id | As Expected | P |  |
| [PUT] update ref-coin | /ref-coins/:id | - | symbol : "TRX | update the spesific attribute in target ref-coin | As Expected | P |  |
|  |  |  | name : "Tron" |  |  |  |  |
|  |  |  | network : "dummy_network_tron_upadete1" |  |  |  |  |
|  |  |  | api_url : "tron_dummy.com" |  |  |  |  |
|  |  |  | flag_enable : true |  |  |  |  |
|  |  |  | pool_wallet : "tron_update" |  |  |  |  |
|  |  |  | description : "dummy_description" |  |  |  |  |

**Comment by drmwnarief28** [comment]
Hasil setelah create :
![image](https://user-images.githubusercontent.com/54920443/143541858-a2c99c21-0206-4f31-9588-6cc582587b3d.png)

Hasil setelah update :
![image](https://user-images.githubusercontent.com/54920443/143541935-96365043-4242-417d-82e6-98deb31f16c2.png)
