### ISSUE TITLE
[QA] Test API CRU Transaction Fee

### ISSUE THREAD

**Issue by anra54** [purwaren/moflip-api#81]

**Comment by drmwnarief28** [comment]
| Aspect Testing | API | Parameter | Request Body | Expected Result | Actual Result | Status (P/F) | Description |
|---|---|---|---|---|---|---|---|
| [POST] create ref-fees | /ref-fees |  | coin_id : 2 | ref-fee created | As Expected | P |  |
|  |  |  | transaction_type : "TOPUP" |  |  |  |  |
|  |  |  | type : "STATIC" |  |  |  |  |
|  |  |  | amount : "0.0000001" |  |  |  |  |
|  |  |  |  |  |  |  |  |
| [GET] ref-fees | /ref-fees | - | - | show list of ref-fees | As Expected | P |  |
| [GET] detail ref-fee | /ref-fees/:id | - | - | show detail of ref fee | As Expected | P |  |
| [PUT] update ref-fee | /ref-fees/:id | - | coin_id : 2 | ref-fee updated | As Expected | P |  |
|  |  |  | transaction_type : "TOPUP" |  |  |  |  |
|  |  |  | type : "STATIC" |  |  |  |  |
|  |  |  | amount : "0.0000011" |  |  |  |  |

**Comment by drmwnarief28** [comment]
hasil setelah created :
![image](https://user-images.githubusercontent.com/54920443/143548880-1f22ec92-6311-4089-9fb0-7e98857e38e5.png)

hasil setelah update :
![image](https://user-images.githubusercontent.com/54920443/143548941-067b00c1-cec3-4cb8-98bd-10971c09c4e6.png)
