### ISSUE TITLE
[QA] Test API CRU Exchange Rate

### ISSUE THREAD

**Issue by anra54** [purwaren/moflip-api#82]

**Comment by drmwnarief28** [comment]
| Aspect Testing | API | Parameter | Request Body | Expected Result | Actual Result | Status (P/F) | Description |
|---|---|---|---|---|---|---|---|
| [POST] create rates | /rates |  | from_coin : "TRX" | rates created | As Expected | P |  |
|  |  |  | to_coin : "BTC" |  |  |  |  |
|  |  |  | rate_value : "0,1" |  |  |  |  |
|  |  |  | start_date : "2021-11-26T08:05:17Z" |  |  |  |  |
|  |  |  | end_date : "2021-12-26T08:05:17Z" |  |  |  |  |
|  |  |  |  |  |  |  |  |
| [GET] rates | /rates | - | - | show list of rates | As Expected | P |  |
| [GET] detail rates | /rates/:id | - | - | show detail of rates | As Expected | P |  |
| [PUT] update rates | /rates/:id | - | from_coin : "TRX" | ref-fee updated | As Expected | P |  |
|  |  |  | to_coin : "BTC" |  |  |  |  |
|  |  |  | rate_value : "0,11" |  |  |  |  |
|  |  |  | start_date : "2021-11-26T08:05:17Z" |  |  |  |  |
|  |  |  | end_date : "2021-12-26T08:05:17Z" |  |  |  |  |
