### ISSUE TITLE
[QA] Test API Generate Wallet

### ISSUE THREAD

**Issue by anra54** [purwaren/moflip-api#83]

**Comment by drmwnarief28** [comment]
| Aspect Testing | API | Parameter | Request Body | Expected Result | Actual Result | Status (P/F) | Description |
|---|---|---|---|---|---|---|---|
| [POST] create wallet | /wallets | - | ref_coin_id : 1 | wallet created | As Expected | P | ref coin BTC |
|  |  |  |  |  |  |  |  |
| [GET] wallets | /wallets | - | - | show list of wallets | As Expected | P |  |
|  |  |  |  |  |  |  |  |
| [GET] detail wallets | /wallets/:id | - | - | show detail of wallets | As Expected | P |  |
